### PR TITLE
Dark Theme

### PR DESCRIPTION
**Pull request by darkerbit**
Just to save some poor eyes :smile: 

It's not the world's cleanest code, but I've tried to keep it simple.

### CODE REVIEW

**Review by Player3324 — APPROVED** [review]
Change looks fine, thanks! I still need to test it.

**Comment by darkerbit** [comment]
There is an apparent issue where the names become unreadable on Modmuss' machine, despite not doing so on mine, so I'll try to fix this later

**Comment by darkerbit** [comment]
Here we go! I think I've gotten the dark theme into a fairly good state :+1: 

image of dark theme

**Review by BeetMacol — APPROVED** [review]
Look really nice. The preference is not saved, but it is not that necessary.

**Comment by NebelNidas** [comment]
Any reason why this was closed? Would be neat to have dark theme support in Matcher

**Pull request closed without merging**
