### PR TITLE
Use Vineflower instead of Fernflower

### PR DESCRIPTION
**Pull request by NebelNidas**
https://github.com/Vineflower/vineflower/pull/120 introduced a much nicer API, allowing us to get rid of the hacky glue code.

### CODE REVIEW

**Review by modmuss50 — APPROVED** [review]
This is better, ideally we would support both but as they share the same package this isnt really that easy.

**Review by Player3324 — APPROVED** [review]

**Comment by Player3324** [comment]
it's conflicting now, please fix when you have a moment

**Comment by NebelNidas** [comment]
So you're fine with replacing Fernflower entirely? I know Modmuss linked to an article on Discord explaining how to keep both via package relocation, but I couldn't quite get it to work and hadn't had time to look at it again

**Comment by Player3324** [comment]
For now I don't see a strong need to support both

**Pull request merged**
